version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - ":6379"
    networks:
      - redis_network
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
    driver: local

networks:
  redis_network:
    driver: bridge
